"""
Django settings for accreditation project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-6_dtbbcn06vbza(@fb+6rl6%f(^7coep16s!p7v)@a+r4t0z-!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Helper to parse comma-separated env values safely
def _csv_env(name: str, default: str = ""):
    return [h.strip() for h in os.getenv(name, default).split(',') if h.strip()]

# Hosts allowed to serve this site. Provide as comma-separated list in env.
ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# If wildcard is explicitly set in env, allow all (useful for quick diagnostics only)
if '*' in ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'firebase_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'accreditation.cache_middleware.FirestoreCacheMiddleware',  # DISABLED - Causes stale data
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accreditation.auth_views.FirebaseAuthMiddleware',  # Our custom auth middleware
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'accreditation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accreditation.context_processors.appearance_settings',  # Add appearance settings globally
            ],
        },
    },
]

WSGI_APPLICATION = 'accreditation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Production uses PostgreSQL, development uses SQLite
if os.getenv('DB_ENGINE') == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE'),
            'NAME': os.getenv('DB_NAME', 'plp_accreditation'),
            'USER': os.getenv('DB_USER', 'plpuser'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    # SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Firebase Firestore is our primary database - configured below


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Authentication
AUTHENTICATION_BACKENDS = [
    'accreditation.firebase_auth.FirebaseAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep as fallback
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Firebase Configuration
FIREBASE_CONFIG = {
    'project_id': 'plp-accreditation',
    'project_number': '659742231759'
}

# Firebase Service Account Path
FIREBASE_SERVICE_ACCOUNT_PATH = BASE_DIR / 'firebase-service-account.json'

# Initialize Firebase Admin SDK
try:
    import firebase_admin
    from firebase_admin import credentials, firestore

    if not firebase_admin._apps:
        try:
            # Check if service account file exists
            if os.path.exists(FIREBASE_SERVICE_ACCOUNT_PATH):
                cred = credentials.Certificate(str(FIREBASE_SERVICE_ACCOUNT_PATH))
                firebase_admin.initialize_app(cred, {
                    'projectId': FIREBASE_CONFIG['project_id']
                })
                print("Firebase initialized successfully!")
            else:
                print("Warning: Firebase service account file not found!")
                print(f"Expected location: {FIREBASE_SERVICE_ACCOUNT_PATH}")
                print("Please download your service account key from Firebase Console.")
        except Exception as e:
            print(f"Error initializing Firebase: {e}")

    # Firestore Database
    try:
        db = firestore.client()
    except Exception as e:
        print(f"Error connecting to Firestore: {e}")
        db = None

except ImportError as e:
    print(f"Firebase packages not available: {e}")
    print("Run: pip install firebase-admin google-cloud-firestore")
    db = None


# Security Settings
X_FRAME_OPTIONS = 'SAMEORIGIN'  # Allow iframes from same origin

# Respect proxy headers (Nginx) for correct host/scheme handling
# Nginx sets X-Forwarded-Proto; we also set X-Forwarded-Host for safety.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production Security Settings (only applied when DEBUG=False)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # CSRF trusted origins for production (env overrides default)
    _csrf_env = _csv_env('CSRF_TRUSTED_ORIGINS', '')
    if _csrf_env:
        CSRF_TRUSTED_ORIGINS = _csrf_env
    else:
        CSRF_TRUSTED_ORIGINS = [
            'https://plpaccreditation.com',
            'https://www.plpaccreditation.com'
        ]

# Email Configuration for OTP Verification
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'accreditationsystem2023@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'tjgh wibm ddtg eqml')
DEFAULT_FROM_EMAIL = f'PLP Accreditation System <{EMAIL_HOST_USER}>'

# OTP Settings
OTP_EXPIRY_MINUTES = 5  # OTP valid for 5 minutes
OTP_LENGTH = 6  # 6-digit OTP

# Cloudinary Configuration (for file/image uploads)
# Cloud name is hardcoded in cloudinary_utils.py: 'dygrh6ztt'
# API credentials should be in environment variables
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')

# Make Cloudinary credentials available to cloudinary_utils.py
if CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    os.environ['CLOUDINARY_API_KEY'] = CLOUDINARY_API_KEY
    os.environ['CLOUDINARY_API_SECRET'] = CLOUDINARY_API_SECRET

